# Configure Cloudflare Worker

name = "baeknote"
compatibility_date = "2025-07-31"
main = "src/index.js"

[[routes]]
pattern = "boj.guide/*"
zone_name = "boj.guide"

[[routes]]
pattern = "boj.guide/problems/*"
zone_name = "boj.guide"

[observability]
enabled = true

[build]
command = "chmod a+x build.sh && ./build.sh"

[assets]
directory = "./public"
not_found_handling = "none"
run_worker_first = [ "/*", "!/", "!/docs/*", "!/problems/*", "!/not_found*", "!/css/*", "!/js/*", "!/*.*" ]
