# Configure Cloudflare Worker

name = "baeknote-hextra"
compatibility_date = "2025-07-31"
main = "src/index.js"

[observability]
enabled = true

[build]
command = "chmod a+x build.sh && ./build.sh"

[assets]
directory = "./public"
not_found_handling = "404-page"
run_worker_first = [ "/*", "!/docs/*", "!/problems/*" ]